### ISSUE TITLE
cant passevent to biab

### ISSUE THREAD

**Issue by fungreenfox** [andrepl/BuildInABox#20]
It worked the first time but didnt fold out a house. Now it stops when trying to mark the chest after saving.
biab ver 0.2.0
bukkit ver git-Bukkit-1.5.2-R0.1-1-g53734d2-b2779jnks (MC: 1.5.2) (Implementing API version 1.5.2-R0.2-SNAPSHOT)
Now, everytime i put down the box on the ground, i get kicked with "read time out".
My server has octacore cpu with 24gb mem, and can handle large schematics.

07:51:45 [INFO] [Alerter]: º6[Alerter]: ºeºf[3] ºaFungreenfoxºf use a command: ºc/biab save strandhusºf
07:51:45 [INFO] Fungreenfox issued server command: /biab save strandhus
07:51:47 [SEVERE] Could not pass event PlayerInteractEvent to BuildInABox v0.2.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:35)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
        at org.bukkit.craftbukkit.v1_5_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:186)
        at net.minecraft.server.v1_5_R3.PlayerInteractManager.dig(PlayerInteractManager.java:108)
        at net.minecraft.server.v1_5_R3.PlayerConnection.a(PlayerConnection.java:541)
        at net.minecraft.server.v1_5_R3.Packet14BlockDig.handle(SourceFile:46)
        at net.minecraft.server.v1_5_R3.Packet14BlockDig$$EnhancerByCGLIB$$82409193.CGLIB$handle$0(<generated>)
        at net.minecraft.server.v1_5_R3.Packet14BlockDig$$EnhancerByCGLIB$$82409193$$FastClassByCGLIB$$5e2194f6.invoke(<generated>)
        at com.comphenix.net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
        at com.comphenix.protocol.injector.packet.ReadPacketModifier.intercept(ReadPacketModifier.java:102)
        at net.minecraft.server.v1_5_R3.Packet14BlockDig$$EnhancerByCGLIB$$82409193.handle(<generated>)
        at net.minecraft.server.v1_5_R3.NetworkManager.b(NetworkManager.java:292)
        at net.minecraft.server.v1_5_R3.PlayerConnection.d(PlayerConnection.java:109)
        at net.minecraft.server.v1_5_R3.ServerConnection.b(SourceFile:35)
        at net.minecraft.server.v1_5_R3.DedicatedServerConnection.b(SourceFile:30)
        at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:581)
        at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:226)
        at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:477)
        at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:410)
        at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
        at com.norcode.bukkit.schematica.Clipboard.getBlock(Clipboard.java:405)
        at com.norcode.bukkit.buildinabox.BuildingPlan.fromClipboard(BuildingPlan.java:135)
        at com.norcode.bukkit.buildinabox.listeners.PlayerListener.onPlayerSelection(PlayerListener.java:74)
        at sun.reflect.GeneratedMethodAccessor238.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
        ... 22 more

**Comment by fungreenfox** [comment]
ArrayIndexOutOfBoundsException leads me to guess for a to small table index, but would probably also count for a sql lite stored index. When i store small objekts, it sometimes works, but other times, plugin crashes and need reload.
The size of the house on your video, stored in a box, is to large for running here, but i can do it with WE manually, even larger buildings.

**Comment by andrepl** [comment]
The array index it's referring to is actually one of the coordinates of the clipboard it's trying to copy, its looking for your enderchest outside of the selected region.. does your selection encompass the enderchest as well?

If you can, please try build #133 from here: http://mcgitlab.norcode.com:8081/job/BuildInABox/133/com.norcode.bukkit.buildinabox$BuildInABox/

If that is the problem, this version will tell you with a nicer error message :)

thanks your your report.

**Comment by fungreenfox** [comment]
Yes, i would, but is a broken link http://mcgitlab.norcode.com:8081/job/BuildInABox/133/com.norcode.bukkit.buildinabox$BuildInABox/

**Comment by andrepl** [comment]
Wierd, github broke the link... try this one http://mcgitlab.norcode.com:8081/job/BuildInABox/133/ but you'll have to click the link at the bottom under 'Module Builds' to get to the jar download.

**Comment by fungreenfox** [comment]
thanks, i went to the page, silly me, could have found dev builds there.

**Comment by fungreenfox** [comment]
i am testing the dev build now, at mcraft.dk

**Comment by fungreenfox** [comment]
well, i get this a lot, when i have said /biab save itemname, and clicking the box:

21:14:14 [SEVERE] Could not pass event PlayerInteractEvent to BuildInABox v0.2.1-SNAPSHOT
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:35)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
        at org.bukkit.craftbukkit.v1_5_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:186)
        at net.minecraft.server.v1_5_R3.PlayerInteractManager.dig(PlayerInteractManager.java:108)
        at net.minecraft.server.v1_5_R3.PlayerConnection.a(PlayerConnection.java:541)
        at net.minecraft.server.v1_5_R3.Packet14BlockDig.handle(SourceFile:46)
        at net.minecraft.server.v1_5_R3.Packet14BlockDig$$EnhancerByCGLIB$$f8660183.CGLIB$handle$0(<generated>)
        at net.minecraft.server.v1_5_R3.Packet14BlockDig$$EnhancerByCGLIB$$f8660183$$FastClassByCGLIB$$49b72f5c.invoke(<generated>)
        at com.comphenix.net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
        at com.comphenix.protocol.injector.packet.ReadPacketModifier.intercept(ReadPacketModifier.java:102)
        at net.minecraft.server.v1_5_R3.Packet14BlockDig$$EnhancerByCGLIB$$f8660183.handle(<generated>)
        at net.minecraft.server.v1_5_R3.NetworkManager.b(NetworkManager.java:292)
        at net.minecraft.server.v1_5_R3.PlayerConnection.d(PlayerConnection.java:109)
        at net.minecraft.server.v1_5_R3.ServerConnection.b(SourceFile:35)
        at net.minecraft.server.v1_5_R3.DedicatedServerConnection.b(SourceFile:30)
        at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:581)
        at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:226)
        at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:477)
        at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:410)
        at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 43
        at com.norcode.bukkit.schematica.Clipboard.getBlock(Clipboard.java:405)
        at com.norcode.bukkit.buildinabox.BuildingPlan.fromClipboard(BuildingPlan.java:135)
        at com.norcode.bukkit.buildinabox.listeners.PlayerListener.onPlayerSelection(PlayerListener.java:74)
        at sun.reflect.GeneratedMethodAccessor193.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
        ... 22 more

**Comment by andrepl** [comment]
It still seems like the enderchest might still be outside of the selected region, on the other side this time, and i didn't catch that.  you are sure that the enderchest you hit is inside of the clipboard region?

I uploaded a new build, if you set 'debug: true' in your config file, it should log some extra information instead of that error message. (enderchest location vs. clipboard size) can you try it again and paste the results?

**Comment by fungreenfox** [comment]
hmm now i get it. its possible it has been placed on the row outside sometimes. I have a lighttower in a box now, which works 90% at the times folded out. Sometimes it will start expand it, and stop after first layer. Smaller selections are cool. It works now, but larger selections is not so good. biab will discard info and fail to pass it, noticeable in the console.

**Comment by andrepl** [comment]
can you paste whatever console output you're getting with `debug: true`

**Comment by fungreenfox** [comment]
hmm i had no errors this time. Tryed with a 20x20 liebhavervilla and no errors with debug on.
03:01:58 [INFO] [Alerter]: º6[Alerter]: ºeºf[14] ºaFungreenfoxºf use a command: ºc/biab save mcdonaldsºf
03:01:58 [INFO] Fungreenfox issued server command: /biab save mcdonalds
03:02:01 [INFO] [BuildInABox] Offset selected.
03:02:01 [INFO] [BuildInABox] Clipboard Copied: {Clipboard[44x48x72]}

**Comment by fungreenfox** [comment]
the chest.yml doesnt look good, and complains to the console at server startup.

05:50:40 [INFO] [BuildInABox] Loading chest: 2
05:50:40 [INFO] [BuildInABox]  ... id 2
05:50:40 [INFO] [BuildInABox]  ... no location data.
05:50:40 [INFO] [BuildInABox] Chest w/ key: 2 has an invalid world.
05:50:40 [INFO] [BuildInABox] Loading chest: 4
05:50:40 [INFO] [BuildInABox]  ... id 4
05:50:40 [INFO] [BuildInABox]  ... no location data.
05:50:40 [INFO] [BuildInABox] Chest w/ key: 4 has an invalid world.
05:50:40 [INFO] [BuildInABox] Loading chest: 5
05:50:40 [INFO] [BuildInABox]  ... id 5
05:50:40 [INFO] [BuildInABox]  ... no location data.
05:50:40 [INFO] [BuildInABox] Chest w/ key: 5 has an invalid world.
05:50:40 [INFO] [BuildInABox] Loading chest: 6
05:50:40 [INFO] [BuildInABox]  ... id 6
05:50:40 [INFO] [BuildInABox]  ... no location data.
05:50:40 [INFO] [BuildInABox] Chest w/ key: 6 has an invalid world.
05:50:40 [INFO] [BuildInABox] Loading chest: 7
05:50:40 [INFO] [BuildInABox]  ... id 7
05:50:40 [INFO] [BuildInABox]  ... no location data.
05:50:40 [INFO] [BuildInABox] Chest w/ key: 7 has an invalid world.
05:50:40 [INFO] [BuildInABox] Loading chest: 10
05:50:40 [INFO] [BuildInABox]  ... id 10
05:50:40 [INFO] [BuildInABox]  ... no location data.
05:50:40 [INFO] [BuildInABox] Chest w/ key: 10 has an invalid world.
05:50:40 [INFO] [BuildInABox] Loading chest: 11
05:50:40 [INFO] [BuildInABox]  ... id 11
05:50:40 [INFO] [BuildInABox]  ... no location data.
05:50:40 [INFO] [BuildInABox] Chest w/ key: 11 has an invalid world.
05:50:40 [INFO] [BuildInABox] Loading chest: 12
05:50:40 [INFO] [BuildInABox]  ... id 12
05:50:40 [INFO] [BuildInABox]  ... no location data.
05:50:40 [INFO] [BuildInABox] Chest w/ key: 12 has an invalid world.
05:50:40 [INFO] [BuildInABox] Loading chest: 13
05:50:40 [INFO] [BuildInABox]  ... id 13
05:50:40 [INFO] [BuildInABox]  ... no location data.
05:50:40 [INFO] [BuildInABox] Chest w/ key: 13 has an invalid world.
05:50:40 [INFO] [BuildInABox] Loading chest: 14
05:50:40 [INFO] [BuildInABox]  ... id 14
05:50:40 [INFO] [BuildInABox]  ... no location data.
05:50:40 [INFO] [BuildInABox] Chest w/ key: 14 has an invalid world.
05:50:40 [INFO] [BuildInABox] Loading chest: 15
05:50:40 [INFO] [BuildInABox]  ... id 15
05:50:40 [INFO] [BuildInABox]  ... no location data.
05:50:40 [INFO] [BuildInABox] Chest w/ key: 15 has an invalid world.
05:50:40 [INFO] [BuildInABox] Loading chest: 16
05:50:40 [INFO] [BuildInABox]  ... id 16
05:50:40 [INFO] [BuildInABox]  ... no location data.
05:50:40 [INFO] [BuildInABox] Chest w/ key: 16 has an invalid world.
05:50:40 [INFO] [BuildInABox] Loading chest: 17
05:50:40 [INFO] [BuildInABox]  ... id 17
05:50:40 [INFO] [BuildInABox]  ... no location data.
05:50:40 [INFO] [BuildInABox] Chest w/ key: 17 has an invalid world.
05:50:40 [INFO] [BuildInABox] Loading chest: 18
05:50:40 [INFO] [BuildInABox]  ... id 18
05:50:40 [INFO] [BuildInABox]  ... location: world1;-794;69;406

**Comment by fungreenfox** [comment]
The only world shown on above list is world1, where there is no GriefPrevention active as the only world without.

**Comment by andrepl** [comment]
That's just debug info because you have debug: true, it's all normal.  you should probably set it to false again to be less spammy. :)

**Comment by fungreenfox** [comment]
Another strange case is passing a box to my alt and letting him build at my ground with trust.
success, but one frontdoor needed to be corrected as it opened asyncronous. So i delete my file and makes a new one. Now i get errors when my alt wants to spawn the box, and the box wont loosen from the ground.

07:06:47 [WARNING] [BuildInABox] Task #3150 for BuildInABox v0.2.1-SNAPSHOT generated an exception
java.lang.NullPointerException
        at com.norcode.bukkit.schematica.Clipboard.copyBlockToWorld(Clipboard.java:624)
        at com.norcode.bukkit.buildinabox.BuildChest$4.processBlock(BuildChest.java:334)
        at com.norcode.bukkit.buildinabox.BuildManager$BuildTask.tick(BuildManager.java:90)
        at com.norcode.bukkit.buildinabox.BuildManager.run(BuildManager.java:41)
        at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftTask.run(CraftTask.java:53)
        at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
        at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:513)
        at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:226)
        at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:477)
        at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:410)
        at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)

**Comment by andrepl** [comment]
thanks, i'm going to open a separate ticket for this and look into it tomorrow.

https://github.com/andrepl/BuildInABox/issues/22

**Comment by fungreenfox** [comment]
i dont know what you mean, npe? my mistake here might have been trying to use the same box without exchanging it to the new one with same name.

**Comment by fungreenfox** [comment]
ah ok. NPE yes. hehe had to look again.

**Comment by andrepl** [comment]
NullPointerException :)
