### ISSUE TITLE
1.6.2 no way

### ISSUE THREAD

**Issue by fungreenfox** [andrepl/BuildInABox#33]
The version for craftbukkit 1.6 is not working. Sales can not be done. Lists will only show the amount of commands available, and should have been showing a list of boxes.

**Comment by andrepl** [comment]
BuildInABox uses Craftbukkit code, so it will always need updating for every new craftbukkit version... starting with [build 166](http://mcgitlab.norcode.com:8081/job/BuildInABox/lastStableBuild/)  we're now compiling for 1.6.1 (there is no 1.6.2 craftbukkit yet).

**Comment by fungreenfox** [comment]
i am currently at 1.6.1 and it doesnt work. I just thought you had made one for that. 
I am following the devs builds, so im upgrading aswell to 1.6.2.

**Comment by andrepl** [comment]
can you post your server log? there is no 1.6.2 craftbukkit, not even dev builds.  BIAB build #166 is the first one to have 1.6 support and it's only about 1 or 2 hours old as of right now.

**Comment by fungreenfox** [comment]
![2013-07-05_20 41 45](https://f.cloud.github.com/assets/3235334/755161/d3d88886-e5a2-11e2-96ef-ccdc08f47794.png)
well, the server log doesnt provide any useful information. but i have a screenshot showing.
http://mcraft.dk/downloads/biab/server.log

**Comment by andrepl** [comment]
I've got jenkins build 166 running fine w/ the latest craftbukkit development build.  there's something wrong on your end. the server.log from the very beginning showing the craftbukkit version as well as biab loading and enabling successfully would be useful to see.  if its not providing any output try enabled debug in the config

**Comment by fungreenfox** [comment]
20:50:53 [INFO] This server is running CraftBukkit version git-Bukkit-1.5.2-R1.0-17-g1c07781-b2807jnks (MC: 1.6.1) (Implementing API version 1.6.1-R0.1-SNAPSHOT)

i can try run it with debug.

**Comment by fungreenfox** [comment]
its enough to enable debug in biab?

**Comment by andrepl** [comment]
yes but please include the whole file from startup until you run the command.

**Comment by fungreenfox** [comment]
ok find the link to the server.log above. both server and biab was in debug mode.

**Comment by andrepl** [comment]
This was in your log:

```
    2013-07-05 21:03:52 [SEVERE] Error occurred while enabling BuildInABox v0.2.1-SNAPSHOT (Is it up to date?)
    java.lang.NoClassDefFoundError: net/minecraft/server/v1_5_R3/NBTCompressedStreamTools
            at com.norcode.bukkit.buildinabox.util.SerializationUtil.deserializeCompoundTag(SerializationUtil.java:126)
            at com.norcode.bukkit.buildinabox.util.SerializationUtil.deserializeTileEntities(SerializationUtil.java:148)
            at com.norcode.bukkit.buildinabox.datastore.YamlDataStore.loadChests(YamlDataStore.java:92)
            at com.norcode.bukkit.buildinabox.datastore.YamlDataStore.load(YamlDataStore.java:136)
            at com.norcode.bukkit.buildinabox.BuildInABox.initializeDataStore(BuildInABox.java:291)
            at com.norcode.bukkit.buildinabox.BuildInABox.onEnable(BuildInABox.java:91)
            at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
            at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457)
            at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
            at org.bukkit.craftbukkit.v1_6_R1.CraftServer.loadPlugin(CraftServer.java:282)
            at org.bukkit.craftbukkit.v1_6_R1.CraftServer.enablePlugins(CraftServer.java:264)
            at net.minecraft.server.v1_6_R1.MinecraftServer.l(MinecraftServer.java:313)
            at net.minecraft.server.v1_6_R1.MinecraftServer.f(MinecraftServer.java:290)
            at net.minecraft.server.v1_6_R1.MinecraftServer.a(MinecraftServer.java:250)
            at net.minecraft.server.v1_6_R1.DedicatedServer.init(DedicatedServer.java:151)
            at net.minecraft.server.v1_6_R1.MinecraftServer.run(MinecraftServer.java:391)
            at net.minecraft.server.v1_6_R1.ThreadServerApplication.run(SourceFile:582)
    Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_5_R3.NBTCompressedStreamTools
            at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:70)
            at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
            at java.lang.ClassLoader.loadClass(Unknown Source)
            at java.lang.ClassLoader.loadClass(Unknown Source)
            ... 17 more
```

it really looks like you're not running the latest BIAB. [Jenkins build 166](http://mcgitlab.norcode.com:8081/job/BuildInABox/lastSuccessfulBuild/)

**Comment by fungreenfox** [comment]
thats what i have been trying to tell you before, but you didnt react

**Comment by andrepl** [comment]
I don't understand the problem I guess.  

You are having trouble because you are using a 1.5.2 version of BIAB on a 1.6.1 craftbukkit, if you download the latest BIAB you should have no more trouble, right?

**Comment by fungreenfox** [comment]
If your plugin is ok, then i probably shouldnt have anymore. But i have checked the data size and it matches the latest. I am a freak about getting the right plugin normally, so i wont image it should be another. Ill replace it anyway when i can at next restart, when server is empty.

**Comment by fungreenfox** [comment]
Reinstalled biab and it works, though has some not so good outputs.
http://mcraft.dk/downloads/biab/server.log
